title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Harry Bottle"
    weight = 1
    languageName = 'English'
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.zh]
    title = "Harry Bottle 中文"
    weight = 2
    languageName = '中文'
    contentDir = "content/zh"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "angryangus"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke_socials]
[params.ananke_socials.twitter]  
name = "twitter"
url = "https://twitter.com/zhouzh2"

[params.ananke_socials.youtube]
name = "youtube"
url = "https://www.youtube.com/@zhouzh2"

[params.ananke_socials.github]
name = "github"
url = "https://github.com/zhouzh2"

[params.ananke_socials.slack]
name = "slack"
url = "https://srcbretail.slack.com/"